openapi: 3.0.4

info: 
  title: AlgaShop - Ordering
  version: "1.0"

servers:
  - description: Development
    url: "http://localhost:8080"
  - description: Produtcion
    url: "https://api.algashop.com"