openapi: 3.0.4

info: 
  title: AlgaShop - Ordering
  version: "1.0"

servers:
  - description: Development
    url: "http://localhost:8080"
  - description: Produtcion
    url: "https://api.algashop.com"


paths:
  /api/v1/customers:
    post:
      description: Register a new /api/v1/customers
      tags:
        - Customers
    get:
      description: List Customers
      tags:
        - Customers
  /api/v1/customers/{customerId}:
    get:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: '6e148bd5-47f6-4022-b9da-07cfaa294f7a'
          description: Get one customer by id
          tags:
            - Customers
    put:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: '6e148bd5-47f6-4022-b9da-07cfaa294f7a'
          description: Edit customer
          tags:
            - Customers
    delete:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: '6e148bd5-47f6-4022-b9da-07cfaa294f7a'
          description: Delete customer
          tags:
            - Customers

